### ISSUE TITLE
[WEBFORM-1006] : Font color turns to black and zooms incorrectly for first slide in IE

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-.NET#47]
This issue was originally raised via forum thread: http://www.groupdocs.com/Community/forums/thread/13647/docx-and-ppt-do-not-render-correctly-in-ie.aspx

The font color and size for the first slide in [sample.ppt](https://dl.dropboxusercontent.com/u/72112099/SampleDocsViewer/sample.pptx) is not rendered correctly in IE. Back-end API renders page into html correctly. But the issue appears when the page is loaded inside viewer in front end application in Internet Explorer.

![sampleppt](https://cloud.githubusercontent.com/assets/16013722/16390946/5e3897d0-3cbe-11e6-9fb4-48fff5bb7a94.PNG)

**Comment by PuneetRajak** [comment]
Hi
I have implemented the latest sample solution provided by Groupdocs which solve my issues with above file.
Though I am getting some more issue of incorrect rendering in some PDF file.
attached is the issuing document with issue screenshot.
[DocumentScreenShot.zip](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET/files/351987/DocumentScreenShot.zip)

let me know if something else is required.

**Comment by groupdocs-viewer** [comment]
@PuneetRajak Thanks, glad to hear the original issue is resolved. We'll check the new issues soon.

**Comment by groupdocs-viewer** [comment]
@PuneetRajak The new issues you mentioned can't be reproduced on Internet Explorer 11. Please share the complete details to reproduce the issue. Thanks

**Comment by PuneetRajak** [comment]
Thanks for investigating this.
though the issue is still replicable for us in group docs sample solution.
I have shared a copy of sample solution in which the issue is replicable  for us.
Please add Viewer licence/DLL and run both the issuing PDF to identify the issue.
Please follow the screenshot shared in last post for more details and exact location of incorrect rendering.
do let me know if you want further details, or screen recording.
[ASP.NET_WebForm_Front_End - SampleSolution.zip](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET/files/358824/ASP.NET_WebForm_Front_End.-.SampleSolution.zip)

Thanks
Puneet Rajak

**Comment by groupdocs-viewer** [comment]
Hi Puneet,

Thanks for the explanation and sharing your sample solution.
We have tested your sample at different systems but never reproduce any issue even in all browsers. Therefore, please confirm that the issue is frequently reproducible?
In the cases of large files, the viewer apply the css against each newly loaded page. it may change the look of already loaded pages for a very little time. Finally, the all loaded pages gets it exact shape. So we cannot consider this as an issue. However, if you say that the disturbed pages never corrected automatically after short time then please write to us the exact/specific case.

Thanks
